export const GAME_STATUS_CODE = {
  LOGIN_FAILED: -1,
  NOT_STARTED: 0,
  LOGGING_IN: 1,
  RUNNING: 2,
  GAME_ERROR: 3,
} as const;

export const GAME_LOG_QUERYABLE_STATUS_CODES: readonly number[] = [
  GAME_STATUS_CODE.LOGGING_IN,
  GAME_STATUS_CODE.RUNNING,
  GAME_STATUS_CODE.GAME_ERROR,
];
