name: Auto Build to Server

on:
  push:
    branches:
      - master  # 你的主要分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        debug: true
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: ${{ secrets.SERVER_COMMAND }}

